targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        generate_for:
          include:
            - lib/di/**
      json_serializable:
        generate_for:
          include:
            - lib/data/**
           
