name: movie_app_clean_architecture
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  injectable: ^2.4.1
  shared_preferences: ^2.2.3
  http: ^1.2.2
  equatable: ^2.0.5

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.5.0

flutter:
  uses-material-design: true
