name: movie_app_clean_architecture
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  envied:
  flutter:
    sdk: flutter
  get_it:
  google_fonts:
  injectable:
  shared_preferences:

dev_dependencies:
  build_runner:
  envied_generator:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator:

flutter:
  uses-material-design: true
